//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Meridium.Excel {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ExcelResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ExcelResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Meridium.Excel.ExcelResources", typeof(ExcelResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Datasource (filepath) parameter is null or empty.
        /// </summary>
        internal static string DataSourceEmpty {
            get {
                return ResourceManager.GetString("DataSourceEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Datatable parameter is null.
        /// </summary>
        internal static string DataTableNull {
            get {
                return ResourceManager.GetString("DataTableNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Microsoft Excel drivers are not installed.
        /// </summary>
        internal static string ExcelNotInstalled {
            get {
                return ResourceManager.GetString("ExcelNotInstalled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not a valid excel sheet.
        /// </summary>
        internal static string NotAnExcel {
            get {
                return ResourceManager.GetString("NotAnExcel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Query array instance is null or empty.
        /// </summary>
        internal static string QueryArrayInstanceEmpty {
            get {
                return ResourceManager.GetString("QueryArrayInstanceEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Query array parameter is null.
        /// </summary>
        internal static string QueryArrayNull {
            get {
                return ResourceManager.GetString("QueryArrayNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Query parameter is null or empty.
        /// </summary>
        internal static string QueryEmpty {
            get {
                return ResourceManager.GetString("QueryEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Schema parameter is null or empty.
        /// </summary>
        internal static string SchemaEmpty {
            get {
                return ResourceManager.GetString("SchemaEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Source table parameter is null or empty.
        /// </summary>
        internal static string SourceTableEmpty {
            get {
                return ResourceManager.GetString("SourceTableEmpty", resourceCulture);
            }
        }
    }
}
